apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-app
  labels:
    app: conversao-app
spec:
  selector:
    matchLabels:
      app: conversao-app
  replicas: 2
  template:
    metadata:
      labels:
        app: conversao-app
    spec:
      containers:
        - name: conversao-app
          image: clsyan/conversao-temperatura:latest


---

apiVersion: v1
kind: Service
metadata:
  name: conversao-app-svc
spec:
  selector:
    app: conversao-app
  ports:
  - port: 8080
    nodePort: 30000
    protocol: TCP
  type: NodePort
